### PR TITLE
Update the Bazel rules to support Bazel 4.0.0

### PR DESCRIPTION
**Pull request by matthewsot**
We were using outdated versions of a few libraries, which caused problems when trying to run things on the latest version(s) of Bazel. This corrects that.

### CODE REVIEW

**Review by adityathakur — APPROVED** [review]
LGTM

**Comment by matthewsot** [comment]
The tests are failing because the CI scripts use a _very_ outdated version of Bazel (1.1.0). I will update the scripts to use the latest version, and update the README.

**Comment by matthewsot** [comment]
Also going to bump the tested Ubuntu version up to 20.04, since it's now the latest LTS release and people have had more than enough time to update.

**Comment by matthewsot** [comment]
Something (I guess with the GRPC dependency) changed where now even the server code is somehow reliant on Python. I think the simplest fix to that will be to modify `bazel_python` to let us pass a flag to silently fall-back on the system Python instead of failing out. We can do that for just the `make start_server` rule and in the test cases above, leaving it to fail if someone tries to run it normally. That should give us the best of both worlds that we already had before (people who just want the server shouldn't have to install bazel-python).

**Pull request merged**
